Repository 9oormthon-univ/2024_DANPOONG_TEAM_50_BE, pull requests merged in 2024-11, with the labels that each got.

#3 1 feature user authentication
  src/main/java/com/example/mymoo/global/auth/controller/AuthController.java
  src/main/java/com/example/mymoo/global/auth/dto/request/AccountLoginRequestDto.java
  src/main/java/com/example/mymoo/global/auth/dto/request/TokenRefreshRequestDto.java
  src/main/java/com/example/mymoo/global/auth/dto/response/AccountLoginResponseDto.java
  src/main/java/com/example/mymoo/global/auth/dto/response/TokenRefreshResponseDto.java
  src/main/java/com/example/mymoo/global/auth/exception/AuthException.java
  src/main/java/com/example/mymoo/global/auth/exception/AuthExceptionDetails.java
  src/main/java/com/example/mymoo/global/auth/repository/AuthRepository.java
  src/main/java/com/example/mymoo/global/auth/repository/impl/AuthRepositoryImpl.java
  src/main/java/com/example/mymoo/global/auth/service/AuthService.java
  src/main/java/com/example/mymoo/global/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/example/mymoo/global/config/RedisConfig.java
  src/main/java/com/example/mymoo/global/config/SecurityConfig.java
  src/main/java/com/example/mymoo/global/config/SwaggerConfig.java
  src/main/java/com/example/mymoo/global/config/WebClientConfig.java
  src/main/java/com/example/mymoo/global/enums/UserRole.java
  src/main/java/com/example/mymoo/global/exception/CustomException.java
  src/main/java/com/example/mymoo/global/exception/ExceptionDetails.java
  src/main/java/com/example/mymoo/global/exception/dto/BeanValidationExceptionResponseDto.java
  src/main/java/com/example/mymoo/global/exception/dto/CustomExceptionResponseDto.java
  src/main/java/com/example/mymoo/global/exception/dto/FieldErrorResponseDto.java
  src/main/java/com/example/mymoo/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/mymoo/global/oauth/controller/OAuthController.java
  src/main/java/com/example/mymoo/global/oauth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/example/mymoo/global/oauth/dto/kakao/KakaoUserInfo.java
  src/main/java/com/example/mymoo/global/oauth/dto/response/KakaoLoginResponseDto.java
  src/main/java/com/example/mymoo/global/oauth/dto/response/KakaoLoginUrlResponseDto.java
  src/main/java/com/example/mymoo/global/oauth/service/OAuthService.java
  src/main/java/com/example/mymoo/global/oauth/service/impl/OauthServiceImpl.java
  src/main/java/com/example/mymoo/global/security/CustomUserDetails.java
  src/main/java/com/example/mymoo/global/security/CustomUserDetailsService.java
  src/main/java/com/example/mymoo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mymoo/global/security/jwt/JwtTokenProvider.java
Labels: :star2: feature

#12 9 feature store domain seed
  src/main/java/com/example/mymoo/domain/donation/entity/Donation.java
  src/main/java/com/example/mymoo/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/com/example/mymoo/domain/donationusage/service/impl/DonationUsageServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/dto/api/GDreamCardResponse.java
  src/main/java/com/example/mymoo/domain/store/dto/api/Head.java
  src/main/java/com/example/mymoo/domain/store/dto/api/Row.java
  src/main/java/com/example/mymoo/domain/store/dto/response/MenuDTO.java
  src/main/java/com/example/mymoo/domain/store/entity/AddressNew.java
  src/main/java/com/example/mymoo/domain/store/entity/AddressOld.java
  src/main/java/com/example/mymoo/domain/store/entity/Like.java
  src/main/java/com/example/mymoo/domain/store/entity/Menu.java
  src/main/java/com/example/mymoo/domain/store/entity/Store.java
  src/main/java/com/example/mymoo/domain/store/exception/StoreException.java
  src/main/java/com/example/mymoo/domain/store/exception/StoreExceptionDetails.java
  src/main/java/com/example/mymoo/domain/store/repository/AddressNewRepository.java
  src/main/java/com/example/mymoo/domain/store/repository/AddressOldRepository.java
  src/main/java/com/example/mymoo/domain/store/repository/LikeRepository.java
  src/main/java/com/example/mymoo/domain/store/repository/MenuRepository.java
  src/main/java/com/example/mymoo/domain/store/repository/StoreRepository.java
  src/main/java/com/example/mymoo/domain/store/seed/StoreSeedService.java
Labels: :star2: feature

#15 10 feature store domain api
  src/main/java/com/example/mymoo/domain/store/controller/StoreController.java
  src/main/java/com/example/mymoo/domain/store/dto/response/MenuListDTO.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreDetailDTO.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreListDTO.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreResponseDTO.java
  src/main/java/com/example/mymoo/domain/store/exception/StoreExceptionDetails.java
  src/main/java/com/example/mymoo/domain/store/service/Impl/StoreServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/service/StoreService.java
  src/main/java/com/example/mymoo/domain/store/util/StoreUtil.java
Labels: :star2: feature

#16 11 feature child domain api
  src/main/java/com/example/mymoo/domain/child/dto/controller/ChildController.java
  src/main/java/com/example/mymoo/domain/child/dto/request/ChildReqeustDTO.java
  src/main/java/com/example/mymoo/domain/child/dto/response/ChildResponseDTO.java
  src/main/java/com/example/mymoo/domain/child/exception/ChildExceptionDetails.java
  src/main/java/com/example/mymoo/domain/child/repository/ChildRepository.java
  src/main/java/com/example/mymoo/domain/child/service/ChildService.java
  src/main/java/com/example/mymoo/domain/child/service/Impl/ChildServiceImpl.java
Labels: :star2: feature

#23 19 refactor store seed and store domain api refactoring
  src/main/java/com/example/mymoo/domain/child/controller/ChildController.java
  src/main/java/com/example/mymoo/domain/donation/entity/Donation.java
  src/main/java/com/example/mymoo/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/controller/StoreController.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreListDTO.java
  src/main/java/com/example/mymoo/domain/store/service/Impl/StoreServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/service/StoreService.java
Labels: :warning: fix, :recycle: refactor

#25 #24 - Account & Child SignUp Intergration
  src/main/java/com/example/mymoo/domain/account/controller/AccountController.java
  src/main/java/com/example/mymoo/domain/account/dto/request/AccountCreateRequestDto.java
  src/main/java/com/example/mymoo/domain/child/controller/ChildController.java
  src/main/java/com/example/mymoo/domain/child/exception/ChildExceptionDetails.java
  src/main/java/com/example/mymoo/domain/child/service/ChildService.java
  src/main/java/com/example/mymoo/domain/child/service/Impl/ChildServiceImpl.java
Labels: :recycle: refactor

#27 #26 - Intergration Account, Child SignUp HOT FIX
  src/main/java/com/example/mymoo/domain/account/controller/AccountController.java
Labels: :x: hotfix

#29 28 feature cicd pipe line
  .github/workflows/workflows.yml
  Dockerfile
  docker-compose.yml
Labels: :star2: feature

#41 #40 - add stars data
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreDetailDTO.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreListDTO.java
  src/main/java/com/example/mymoo/domain/store/entity/Store.java
Labels: :x: hotfix

#42 #35 - Implement API Performance Measurement Logging with AOP
  src/main/java/com/example/mymoo/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/mymoo/domain/child/service/Impl/ChildServiceImpl.java
  src/main/java/com/example/mymoo/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/com/example/mymoo/domain/donationusage/service/impl/DonationUsageServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/service/Impl/StoreServiceImpl.java
  src/main/java/com/example/mymoo/global/aop/LogExecutionTime.java
  src/main/java/com/example/mymoo/global/aop/TimeTraceAop.java
Labels: :star2: feature

#43 37 feature bookmark domain api
  src/main/java/com/example/mymoo/domain/store/controller/StoreController.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreListDTO.java
  src/main/java/com/example/mymoo/domain/store/dto/response/StoreResponseDTO.java
  src/main/java/com/example/mymoo/domain/store/entity/BookMark.java
  src/main/java/com/example/mymoo/domain/store/repository/BookMarkRepository.java
  src/main/java/com/example/mymoo/domain/store/service/Impl/StoreServiceImpl.java
  src/main/java/com/example/mymoo/domain/store/service/StoreService.java
Labels: :star2: feature

#44 32 feature integrate kakao pay open api for point payment feature
  src/main/java/com/example/mymoo/domain/payment/controller/PaymentController.java
  src/main/java/com/example/mymoo/domain/payment/dto/api/KakaoPayApproveRequest.java
  src/main/java/com/example/mymoo/domain/payment/dto/api/KakaoPayApproveResponse.java
  src/main/java/com/example/mymoo/domain/payment/dto/api/KakaoPayReadyRequest.java
  src/main/java/com/example/mymoo/domain/payment/dto/api/KakaoPayReadyResponse.java
  src/main/java/com/example/mymoo/domain/payment/dto/request/PayRequestDTO.java
  src/main/java/com/example/mymoo/domain/payment/dto/response/PayResponseDTO.java
  src/main/java/com/example/mymoo/domain/payment/exception/PaymentException.java
  src/main/java/com/example/mymoo/domain/payment/exception/PaymentExceptionDetails.java
  src/main/java/com/example/mymoo/domain/payment/service/Impl/PaymentServiceImpl.java
  src/main/java/com/example/mymoo/domain/payment/service/PaymentService.java
Labels: :star2: feature

#49 38 feature donation statics domain api
  src/main/java/com/example/mymoo/MymooApplication.java
  src/main/java/com/example/mymoo/domain/account/controller/AccountController.java
  src/main/java/com/example/mymoo/domain/account/dto/request/AccountCreateRequestDto.java
  src/main/java/com/example/mymoo/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/mymoo/domain/child/entity/Child.java
  src/main/java/com/example/mymoo/domain/child/entity/Location.java
  src/main/java/com/example/mymoo/domain/child/repository/LocationRepository.java
  src/main/java/com/example/mymoo/domain/child/service/ChildService.java
  src/main/java/com/example/mymoo/domain/child/service/Impl/ChildServiceImpl.java
  src/main/java/com/example/mymoo/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/com/example/mymoo/domain/donationusage/service/impl/DonationUsageServiceImpl.java
  src/main/java/com/example/mymoo/domain/payment/service/Impl/PaymentServiceImpl.java
  src/main/java/com/example/mymoo/domain/statistics/controller/StatisticsController.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/ChildStatisticsDTO.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/ChildStatisticsElement.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/StoreStatisticsDTO.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/StoreStatisticsElement.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/UtilizationStatisticsDTO.java
  src/main/java/com/example/mymoo/domain/statistics/dto/response/UtilizationStatisticsElement.java
  src/main/java/com/example/mymoo/domain/statistics/service/Impl/StatisticsServiceImpl.java
  src/main/java/com/example/mymoo/domain/statistics/service/StatisticsService.java
  src/main/java/com/example/mymoo/domain/store/repository/AddressNewRepository.java
  src/main/java/com/example/mymoo/domain/store/repository/StoreRepository.java
  src/main/java/com/example/mymoo/domain/store/seed/StoreSeedService.java
  src/main/java/com/example/mymoo/domain/store/service/Impl/StoreServiceImpl.java
  src/main/java/com/example/mymoo/global/aop/log/LogExecutionTime.java
  src/main/java/com/example/mymoo/global/aop/log/TimeTraceAop.java
Labels: :star2: feature
